# Generated by Django 6.0.6 on 2026-06-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('motivation', models.TextField(verbose_name='Motivation')),
                ('competences', models.TextField(blank=True, verbose_name="Compétences et domaines d'expertise")),
                ('cv', models.FileField(blank=True, null=True, upload_to='adhesions/cv/', verbose_name='CV')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='adhesions/lettres/', verbose_name='Lettre de motivation')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', 'En cours de traitement')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name="Commentaire de l'administrateur")),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': "Demande d'adhésion",
                'verbose_name_plural': "Demandes d'adhésion",
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la fonction')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/', verbose_name='Photo')),
                ('statut', models.CharField(blank=True, max_length=100, verbose_name='Statut')),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('date_adhesion', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Membre actif')),
                ('est_membre_bureau', models.BooleanField(default=False, verbose_name='Membre du Bureau Exécutif')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('researchgate', models.URLField(blank=True, verbose_name='ResearchGate')),
                ('google_scholar', models.URLField(blank=True, verbose_name='Google Scholar')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membres.fonction', verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-est_membre_bureau', 'fonction__ordre', 'nom', 'prenom'],
            },
        ),
    ]
