# Generated by Django 4.2.7 on 2026-07-04 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeadhesion',
            name='membre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_adhesion', to='membres.membre', verbose_name='Membre associé'),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_invitation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de l'invitation"),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='membre',
            name='est_compte_active',
            field=models.BooleanField(default=False, verbose_name='Compte activé'),
        ),
        migrations.AddField(
            model_name='membre',
            name='token_activation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Token d'activation"),
        ),
        migrations.AddField(
            model_name='membre',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration du token"),
        ),
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_membre', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
        migrations.AlterField(
            model_name='demandeadhesion',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('en_cours', 'En cours de traitement'), ('invitation_envoyee', 'Invitation envoyée'), ('compte_active', 'Compte activé')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='HistoriqueEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_email', models.CharField(choices=[('invitation', 'Invitation à activer le compte'), ('rappel', "Rappel d'activation"), ('confirmation', "Confirmation d'activation"), ('refus', 'Refus de la demande'), ('validation', 'Validation de la demande')], max_length=20, verbose_name="Type d'email")),
                ('sujet', models.CharField(max_length=255, verbose_name='Sujet')),
                ('destinataire', models.EmailField(max_length=254, verbose_name='Destinataire')),
                ('contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token associé')),
                ('statut', models.CharField(choices=[('envoye', 'Envoyé'), ('erreur', 'Erreur'), ('en_attente', 'En attente')], default='envoye', max_length=20, verbose_name='Statut')),
                ('message_erreur', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('ip_admin', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP de l'admin")),
                ('admin_nom', models.CharField(blank=True, max_length=100, verbose_name="Nom de l'admin")),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_emails', to='membres.demandeadhesion', verbose_name='Demande associée')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_emails', to='membres.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': "Historique d'email",
                'verbose_name_plural': 'Historique des emails',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
