# Generated by Django 4.2.7 on 2026-07-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0002_demandeadhesion_membre_membre_date_invitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation"),
        ),
        migrations.AddField(
            model_name='membre',
            name='email_envoye',
            field=models.BooleanField(default=False, verbose_name='Email envoyé'),
        ),
    ]
