# Generated by Django 5.2.16 on 2026-07-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0003_membre_date_acceptation_membre_email_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='entite',
            field=models.CharField(choices=[('association', 'BETA-Résilience Association'), ('bureau_etude', "BETA-Résilience Bureau d'étude"), ('invest', 'BETA-Résilience INVEST'), ('laboratoire', 'Laboratoire Résilience')], default='association', max_length=20, verbose_name='Entité'),
        ),
    ]
