# Generated by Django 4.2.30 on 2026-09-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0007_demandeadhesion_entite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membres.fonction', verbose_name='Fonction'),
        ),
    ]
