# Generated by Django 6.0.6 on 2026-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('general', 'Demande générale'), ('projet', 'Projet / Collaboration'), ('adhesion', 'Adhésion'), ('partenariat', 'Partenariat'), ('service', 'Demande de service'), ('autre', 'Autre')], default='general', max_length=20, verbose_name='Sujet')),
                ('sujet_personnalise', models.CharField(blank=True, max_length=200, verbose_name='Sujet personnalisé')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('est_repondu', models.BooleanField(default=False, verbose_name='Répondu')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
