# Generated by Django 6.0.6 on 2026-06-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du service')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description_courte', models.TextField(max_length=300, verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, verbose_name='Description longue')),
                ('icone', models.CharField(default='fas fa-cog', max_length=100, verbose_name='Icône Font Awesome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name="Image d'illustration")),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Service actif')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name="Mis en avant sur l'accueil")),
                ('meta_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avantage', models.CharField(max_length=300, verbose_name='Avantage')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avantages', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Avantage',
                'verbose_name_plural': 'Avantages',
                'ordering': ['ordre'],
            },
        ),
    ]
