# Generated by Django 6.0.6 on 2026-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Description SEO')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Image de couverture')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('is_in_menu', models.BooleanField(default=True, verbose_name='Dans le menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BETA-Résilience', max_length=100, verbose_name='Nom du site')),
                ('site_tagline', models.CharField(blank=True, max_length=200, verbose_name='Slogan')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email général')),
                ('email_contact', models.EmailField(blank=True, help_text='Email pour les formulaires de contact', max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('phone_whatsapp', models.CharField(blank=True, max_length=50, verbose_name='WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('boite_postale', models.CharField(blank=True, default='BP 8085 Yaoundé - Cameroun', max_length=50, verbose_name='Boîte postale')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Description SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Mots-clés SEO')),
                ('primary_color', models.CharField(default='#2E7D32', max_length=20, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#4CAF50', max_length=20, verbose_name='Couleur secondaire')),
                ('accent_color', models.CharField(default='#FF6F00', max_length=20, verbose_name="Couleur d'accent")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('logo_footer', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo pour le footer')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texte du footer')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='Copyright')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
