# Generated by Django 6.0.6 on 2026-06-19 14:19

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='fas fa-tag', max_length=100, verbose_name='Icône Font Awesome')),
                ('couleur', models.CharField(default='#2E7D32', help_text='Code hexadécimal', max_length=20, verbose_name='Couleur')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "Catégorie d'actualité",
                'verbose_name_plural': "Catégories d'actualités",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('contenu', ckeditor.fields.RichTextField(verbose_name='Contenu')),
                ('extrait', models.TextField(blank=True, max_length=300, verbose_name='Extrait')),
                ('image_couverture', models.ImageField(blank=True, help_text="Image principale de l'article (format 16:9 recommandé)", null=True, upload_to='actualites/%Y/%m/', verbose_name='Image de couverture')),
                ('images_supplementaires', models.JSONField(blank=True, default=list, verbose_name='Images supplémentaires')),
                ('video', models.URLField(blank=True, verbose_name='Lien vidéo (YouTube)')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_evenement', models.DateField(blank=True, null=True, verbose_name="Date de l'événement (si applicable)")),
                ('date_programmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de programmation')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé'), ('programme', 'Programmé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_a_la_une', models.BooleanField(default=False, verbose_name='À la une')),
                ('est_en_avant', models.BooleanField(default=False, verbose_name='En avant')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (séparés par des virgules)')),
                ('nb_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('nb_partages', models.PositiveIntegerField(default=0, verbose_name='Nombre de partages')),
                ('nb_commentaires', models.PositiveIntegerField(default=0, verbose_name='Nombre de commentaires')),
                ('meta_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Description SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='Mots-clés SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='membres.membre', verbose_name='Auteur')),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='actualites.categorieactualite', verbose_name='Catégories')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
                'get_latest_by': 'date_publication',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('est_signale', models.BooleanField(default=False, verbose_name='Signalé')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='actualites.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug', 'est_publie'], name='actualites__slug_0cab22_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['date_publication'], name='actualites__date_pu_b6c67d_idx'),
        ),
    ]
