# Generated by Django 6.0.6 on 2026-06-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='fas fa-folder', max_length=100, verbose_name='Icône Font Awesome')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_publique', models.BooleanField(default=True, verbose_name='Visible par tous')),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('taille', models.BigIntegerField(default=0, editable=False, verbose_name='Taille (octets)')),
                ('type_fichier', models.CharField(default='', editable=False, max_length=50, verbose_name='Type de fichier')),
                ('nom_fichier_original', models.CharField(default='', editable=False, max_length=200, verbose_name='Nom original')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('date_publication', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateField(auto_now=True, verbose_name='Date de modification')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_telechargeable', models.BooleanField(default=True, verbose_name='Téléchargeable')),
                ('est_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('nb_telechargements', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('accessible_aux_membres_seulement', models.BooleanField(default=False, help_text="Cocher pour que ce document ne soit accessible qu'aux membres connectés", verbose_name='Réservé aux membres')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.categoriedocument', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['categorie', 'ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('fichier', models.FileField(upload_to='documents/versions/%Y/%m/', verbose_name='Fichier')),
                ('taille', models.BigIntegerField(default=0, editable=False, verbose_name='Taille (octets)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes de version')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['categorie', 'est_publie'], name='documents_d_categor_472da5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['slug'], name='documents_d_slug_3df491_idx'),
        ),
    ]
