# Generated by Django 4.2.7 on 2026-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entite', models.CharField(choices=[('association', 'BETA-Résilience Association'), ('bureau_etude', "BETA-Résilience Bureau d'étude"), ('invest', 'BETA-Résilience INVEST'), ('laboratoire', 'Laboratoire Résilience')], max_length=20, verbose_name='Entité concernée')),
                ('type_demande', models.CharField(max_length=50, verbose_name='Type de demande')),
                ('autre_type', models.CharField(blank=True, max_length=100, verbose_name='Autre type (précisez)')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('societe', models.CharField(blank=True, max_length=200, verbose_name='Société / Institution')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet de la demande')),
                ('message', models.TextField(verbose_name='Message')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='demandes/%Y/%m/', verbose_name='Document joint')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('rejete', 'Rejeté')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire_admin', models.TextField(blank=True, verbose_name="Commentaire de l'administrateur")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
