# Generated by Django 4.2.30 on 2026-09-29 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demandes', '0002_demande_fichier_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_entites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé'),
        ),
    ]
