# Generated by Django 6.0.6 on 2026-06-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('type_partenaire', models.CharField(choices=[('institutionnel', 'Institutionnel'), ('technique', 'Technique'), ('financier', 'Financier'), ('academique', 'Académique'), ('associatif', 'Associatif'), ('prive', 'Privé')], default='institutionnel', max_length=20, verbose_name='Type')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Partenaire actif')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
