# Generated by Django 4.2.7 on 2026-07-08 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='fas fa-comments', max_length=50, verbose_name='Icône Font Awesome')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie de forum',
                'verbose_name_plural': 'Catégories de forums',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ForumSujet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_epingle', models.BooleanField(default=False, verbose_name='Épinglé')),
                ('est_ferme', models.BooleanField(default=False, verbose_name='Fermé')),
                ('nb_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('dernier_message', models.DateTimeField(auto_now=True, verbose_name='Dernier message')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets_forum', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sujets', to='forums.forumcategorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Sujet de forum',
                'verbose_name_plural': 'Sujets de forum',
                'ordering': ['-est_epingle', '-dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='ForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_edite', models.BooleanField(default=False, verbose_name='Édité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_forum', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forums.forumsujet', verbose_name='Sujet')),
            ],
            options={
                'verbose_name': 'Message de forum',
                'verbose_name_plural': 'Messages de forum',
                'ordering': ['date_creation'],
            },
        ),
    ]
