# Generated by Django 4.2.7 on 2026-07-08 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('type_evenement', models.CharField(choices=[('conference', 'Conférence'), ('atelier', 'Atelier'), ('webinaire', 'Webinaire'), ('sortie_terrain', 'Sortie terrain'), ('assemblee', 'Assemblée générale'), ('reunion', 'Réunion'), ('formation', 'Formation'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('programme', models.TextField(blank=True, verbose_name='Programme')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('lieu', models.CharField(max_length=300, verbose_name='Lieu')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('capacite_max', models.PositiveIntegerField(default=50, verbose_name='Capacité maximale')),
                ('places_restantes', models.PositiveIntegerField(default=50, verbose_name='Places restantes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name="Image de l'événement")),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='a_venir', max_length=20, verbose_name='Statut')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_gratuit', models.BooleanField(default=True, verbose_name='Gratuit')),
                ('prix', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('intervenants', models.TextField(blank=True, verbose_name='Intervenants')),
                ('document', models.FileField(blank=True, null=True, upload_to='evenements/documents/', verbose_name='Document associé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('en_attente', 'En attente'), ('annule', 'Annulé'), ('liste_attente', "Liste d'attente")], default='confirme', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='evenements.evenement', verbose_name='Événement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Inscription à un événement',
                'verbose_name_plural': 'Inscriptions aux événements',
                'ordering': ['date_inscription'],
                'unique_together': {('evenement', 'utilisateur')},
            },
        ),
    ]
