# Generated by Django 4.2.7 on 2026-07-09 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notifications sur le site')),
                ('email_resume_quotidien', models.BooleanField(default=False, verbose_name='Résumé quotidien par email')),
                ('types_actives', models.JSONField(blank=True, default=list, verbose_name='Types de notifications actives')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('demande_validee', '✅ Demande validée'), ('demande_refusee', '❌ Demande refusée'), ('demande_en_cours', '🔄 Demande en cours'), ('demande_recue', '📩 Demande reçue'), ('nouveau_document', '📄 Nouveau document'), ('evenement_proche', '📅 Événement proche'), ('evenement_annule', '❌ Événement annulé'), ('evenement_ajoute', '📅 Nouvel événement'), ('rappel_activation', "⏰ Rappel d'activation"), ('bienvenue', '👋 Bienvenue'), ('message_forum', '💬 Nouveau message'), ('reponse_demande', '📝 Réponse à votre demande'), ('systeme', '⚙️ Information système')], max_length=30, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien')),
                ('est_lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
