# Generated by Django 4.2.30 on 2026-09-29 11:06

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membres', '0008_alter_membre_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_fix_fk_cascade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageprive',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='messageprive',
            name='objet',
        ),
        migrations.AddField(
            model_name='messageprive',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messages_prives/%Y/%m/', validators=[apps.notifications.models.valider_fichier_message], verbose_name='Pièce jointe'),
        ),
        migrations.AddField(
            model_name='messageprive',
            name='membre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='membres.membre', verbose_name='Membre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='contenu',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='expediteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_prives_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur'),
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='lu_par_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messageprive',
            name='lu_par_membre',
            field=models.BooleanField(default=False),
        ),
    ]
