# Generated by Django 6.0.6 on 2026-06-19 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partenaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(default='fas fa-tag', max_length=100, verbose_name='Icône Font Awesome')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie de projet',
                'verbose_name_plural': 'Catégories de projets',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description_courte', models.TextField(max_length=300, verbose_name='Description courte')),
                ('description_longue', models.TextField(blank=True, verbose_name='Description longue')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='projets/', verbose_name='Image principale')),
                ('images_supplementaires', models.JSONField(blank=True, default=list, verbose_name='Images supplémentaires')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('boucle', 'Bouclé'), ('suspendu', 'Suspendu'), ('en_attente', 'En attente de lancement')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('est_termine', models.BooleanField(default=False, verbose_name='Terminé')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_mis_en_avant', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('lien_externe', models.URLField(blank=True, verbose_name='Lien externe')),
                ('document_projet', models.FileField(blank=True, null=True, upload_to='projets/documents/', verbose_name='Document du projet')),
                ('meta_titre', models.CharField(blank=True, max_length=200, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='Description SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('categories', models.ManyToManyField(blank=True, related_name='projets', to='projets.categorieprojet', verbose_name='Catégories')),
                ('partenaires', models.ManyToManyField(blank=True, related_name='projets', to='partenaires.partenaire', verbose_name='Partenaires')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ProjetEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'étape")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('est_realisee', models.BooleanField(default=False, verbose_name='Réalisée')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projets.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Étape de projet',
                'verbose_name_plural': 'Étapes de projet',
                'ordering': ['ordre', 'date_debut'],
            },
        ),
    ]
